apache2:
  Timeout: 350
  KeepAlive: "On"
  MaxKeepAliveRequests: 100
  KeepAliveTimeout: 5
  HostnameLookups: "Off"
  LogLevel: "warn"
  AccessFileName: ".htaccess"
  VirtualHosts:
  - ServerName: "www.projekt.dev"
    ServerAlias: "projekt.dev"
    Address: "*:80"
    Enabled: True
  - ServerName: "www.projekt2.dev"
    ServerAlias: "projekt2.dev"
    Address: "*:80"
    Enabled: True


pureftpd_users:
  - name: test
    dir: /var/www/www.projekt.dev
    password: "razdwatrzy"
  - name: test2
    dir: /var/www/www.projekt2.dev
    password: "czterypiecszesc"